plugins:
  - "stylelint-order"
rules:
  color-hex-case: "lower"
  color-hex-length: "long"
  color-no-invalid-hex: true
  color-named: "never"
  number-leading-zero: "always"
  number-max-precision: 5
  number-no-trailing-zeros: true
  length-zero-no-unit: true
  function-blacklist: []
  function-calc-no-unspaced-operator: true
  function-comma-space-after: "always"
  function-comma-space-before: "never"
  function-linear-gradient-no-nonstandard-direction: true
  function-parentheses-space-inside: "never"
  function-url-quotes: "never"
  function-whitespace-after: "always"
  value-list-comma-newline-after: "never-multi-line"
  value-list-comma-newline-before: "never-multi-line"
  value-list-comma-space-after: "always"
  value-list-comma-space-before: "never"
  unit-blacklist: []
  declaration-bang-space-after: "never"
  declaration-bang-space-before: "always"
  declaration-colon-space-before: "never"
  block-no-empty: true
  block-opening-brace-newline-after: "always"
  block-opening-brace-space-before: "always"
  block-closing-brace-newline-before: "always"
  selector-combinator-space-after: "always"
  selector-combinator-space-before: "always"
  selector-pseudo-element-colon-notation: "double"
  selector-list-comma-newline-after: "always"
  declaration-block-no-duplicate-properties: true
  declaration-block-no-shorthand-property-overrides: true
  declaration-block-trailing-semicolon: "always"
  media-feature-colon-space-after: "always"
  media-feature-colon-space-before: "never"
  media-feature-range-operator-space-after: "always"
  media-feature-range-operator-space-before: "always"
  media-feature-parentheses-space-inside: "never"
  media-query-list-comma-space-after: "always"
  media-query-list-comma-space-before: "never"
  comment-whitespace-inside: "always"
  indentation: 2
  max-empty-lines: 2
  no-eol-whitespace: true
  no-missing-end-of-source-newline: true
